#ifndef WHISPERER_DEVICES_ITE_HEADER
#define WHISPERER_DEVICES_ITE_HEADER

/* Integrated Technology Express, Inc. */
#define WHISPERER_DEVICES_ITE_VID 0x048d

#endif /* WHISPERER_DEVICES_ITE_HEADER */
